QA deploy

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,11 +2,38 @@ variables:
   LANG: C.UTF-8
   LC_ALL: C.UTF-8
   BRANCH_NAME: ci-fix
+  DOCKER_TLS_CERTDIR: "/certs"
+  # GIT_SSL_NO_VERIFY: "true"  # Add this line to ignore SSL verification, because we have self-signed certificate
+
+  # build
+  GIT_DEPTH: 1
+  DOCS_FULL_ARCHIVE_NAME: words-docs.tar.gz
+  DOCS_TEMPLATE_PROJECT_NAME: docs-template
   CI_HOME_FOLDER: /opt/gitlab-words-ci
   HUGO_PATH: $CI_HOME_FOLDER/bins/hugo
+  DOCS_TEMPLATE_BRANCH_NAME: main
+  DOCS_TEMPLATE_CONTAINER_PATH: $CI_HOME_FOLDER/docs-template
+  DOCS_BUILD_OUTPUT: $CI_HOME_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER
+  DOCS_BUILD_OUTPUT_FOLDER: output-static-docs-words
+  DOCS_BUILD_OUTPUT_ARCHIVE: $CI_PROJECT_DIR/output-static-docs-words-archive
+  NPM_REGISTRY_CERT_DIR: $CI_HOME_FOLDER/certs
+  NPM_REGISTRY_CERT_PATH: $NPM_REGISTRY_CERT_DIR/npm-registry-cert.pem
+
+  # deploy
+  COPY_FOLDER: /home/service_words
+  COPY_USER_NAME: service_words
+  COPY_SERVER_ADDRESS: 172.20.4.232
+  SYNC_TYPE: words-qa # "words" (https://docs.aspose.com/words/) or "words-qa" (https://docs.aspose.com/words-qa/)
+  SYNC_FOLDER: /var/www/docs.aspose.com/html/$SYNC_TYPE
 
 stages:
-  - test
+  - build
+  - deploy
+
+default:
+  tags:
+    - documentation
+    - words
 
 .rules:branch:
   rules:
@@ -21,12 +48,10 @@ stages:
     - mkdir -p /etc/apk
     - echo "cache-dir = $APK_CACHE_DIR" > /etc/apk/apk.conf
 
-test:
-  stage: test
+build:
+  stage: build
   image: node:25.9-alpine
   extends: .rules:branch
-  variables:
-    GIT_STRATEGY: none
   cache:
     key: "$CI_COMMIT_REF_SLUG-apk-npm"
     paths:
@@ -36,30 +61,125 @@ test:
   before_script:
     - *apk_cache_setup
     - npm config set cache "$CI_PROJECT_DIR/.npm-cache"
-    - apk add gcompat libstdc++
-  script:
+    # - sed -i 's/https/http/' /etc/apk/repositories
+    # - apk update
+    # - apk add --no-cache openssl ca-certificates
+    # - sed -i 's/http/https/' /etc/apk/repositories
+    # - update-ca-certificates --fresh
+    # - mkdir -p $NPM_REGISTRY_CERT_DIR
+    # - openssl s_client -showcerts -connect registry.npmjs.org:443 </dev/null 2>/dev/null | openssl x509 -outform PEM > $NPM_REGISTRY_CERT_PATH
+    # - echo "HostName $(hostname), RunnerDescription $CI_RUNNER_DESCRIPTION, ProjectDirectory $CI_PROJECT_DIR, Git Depth $GIT_DEPTH, Docs template url $DOCS_TEMPLATE_GIT_URL, Docs template path $DOCS_TEMPLATE_CONTAINER_PATH, The current branch is $CI_COMMIT_REF_NAME"
+    # - echo "Installing Git..."
+    # - apk update && apk add --no-cache git
+    - echo "The current branch is $CI_COMMIT_REF_NAME"
+    - apk add gcompat libstdc++ tar git-lfs
+    - git lfs install
+    - git lfs pull
+    # - git --version
+    # - git lfs version
+    # - node --version
+    # - npm --version
+    # - tar --version
+    # - apk info gcompat
+    # - apk info libstdc++
     - chmod +x $HUGO_PATH
     - $HUGO_PATH version
-
-test_docker_connectivity:
-  stage: test
-  image: docker:29.4
-  extends: .rules:branch
-  variables:
-    # DOCKER_HOST: tcp://gitlab-words-dind:2375
-    DOCKER_TLS_CERTDIR: ""
-    GIT_STRATEGY: none
   script:
-    - docker info
-    - echo "Pulling a test image..."
-    - docker pull alpine:latest
-    - echo "Creating a Hello World Dockerfile..."
+    - echo "Navigate to docs template repository location..."
+    - mkdir -p $DOCS_TEMPLATE_CONTAINER_PATH
+    - cd $DOCS_TEMPLATE_CONTAINER_PATH
+    - echo "Fetch docs template repository..."
+    - git clone --depth $GIT_DEPTH
+      https://$DOCS_TEMPLATE_PROJECT_NAME:$DOCS_TEMPLATE_CI_CD_ACCESS_TOKEN@$DOCS_TEMPLATE_GIT_URL
+      .
+    - echo "Checkout template $DOCS_TEMPLATE_BRANCH_NAME branch..."
+    - git checkout $DOCS_TEMPLATE_BRANCH_NAME
+    - echo "Currently on docs template checked out $(git rev-parse HEAD)
+      revision"
+    - echo "Replace content path in the docs.aspose.com-words.toml..."
+    - sed -i "s|../md-words|$CI_PROJECT_DIR|g"
+      ./configs/docs.aspose.com-words.toml
+    - echo "Current directory $(pwd)"
+    - echo "Intalling project dependencies..."
+    # - npm config set strict-ssl false
+    # - npm config set registry http://registry.npmjs.org/
+    # - npm config set cafile $NPM_REGISTRY_CERT_PATH
+    # - npm config set registry https://registry.npmjs.org
+    - npm ci
+    - echo "Documentation build started..."
+    - $HUGO_PATH --cleanDestinationDir --source $DOCS_TEMPLATE_CONTAINER_PATH
+      --baseURL https://docs.aspose.com/$SYNC_TYPE --contentDir $CI_PROJECT_DIR
+      --config config.toml,configs/docs.aspose.com-words.toml --destination
+      $DOCS_BUILD_OUTPUT --minify --verbose
+    - echo "Documentation build complete, path in the container
+      $DOCS_BUILD_OUTPUT"
+    - echo "Compressing generated documentation..."
+    - cd $CI_HOME_FOLDER
+    - mkdir -p $DOCS_BUILD_OUTPUT_ARCHIVE
+    - tar --warning=all -czvf $DOCS_FULL_ARCHIVE_NAME
+      ./$DOCS_BUILD_OUTPUT_FOLDER > /dev/null
+    - mv ./$DOCS_FULL_ARCHIVE_NAME
+      $DOCS_BUILD_OUTPUT_ARCHIVE/$DOCS_FULL_ARCHIVE_NAME
+    - echo "Documentation compressed."
+  artifacts:
+    paths:
+      - $DOCS_BUILD_OUTPUT_ARCHIVE/$DOCS_FULL_ARCHIVE_NAME
+    expire_in: 10 minutes
+
+.ssh_setup:
+  image: alpine:latest
+  variables:
+    GIT_STRATEGY: none # no git clone
+  before_script:
+    - echo "Adding tools..."
+    - apk add --no-cache openssh-client
+    - mkdir -p ~/.ssh
+    - echo "$COPY_DOCS_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+    - chmod 600 ~/.ssh/id_rsa
+    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
+    - echo "Tools has added and tuned."
+
+deploy:
+  stage: deploy
+  extends:
+    - .rules:branch
+    - .ssh_setup
+  needs:
+    - job: build
+  script:
+    - echo "Transferring documentation archive to $COPY_SERVER_ADDRESS..."
+    - scp $DOCS_BUILD_OUTPUT_ARCHIVE/$DOCS_FULL_ARCHIVE_NAME
+      $COPY_USER_NAME@$COPY_SERVER_ADDRESS:$COPY_FOLDER
+
     - |
-      cat <<EOF > Dockerfile
-      FROM alpine:latest
-      CMD ["echo", "Hello from inside the built image!"]
-      EOF
-    - echo "Building the image..."
-    - docker build -t hello-world-test .
-    - echo "Running the built image..."
-    - docker run --rm hello-world-test
+      echo "Executing remote deployment and synchronization..."
+      ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "
+        # By default, a shell script will keep running even if a command fails. If tar fails, you don't want the script to proceed to rsync an empty folder. set -e forces the script to stop and fail the GitLab job the moment any command returns a non-zero exit code.
+        set -e
+        
+        # 1. Cleanup and Unpack
+        echo 'Unpacking archive...'
+        rm -rf $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER || true
+        tar -xzf $COPY_FOLDER/$DOCS_FULL_ARCHIVE_NAME -C $COPY_FOLDER
+        rm -f $COPY_FOLDER/$DOCS_FULL_ARCHIVE_NAME
+        
+        # 2. Validation
+        if [ ! -d \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\" ] || [ -z \"\$(ls -A \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\")\" ]; then
+          echo 'Error: Source directory is empty or missing.'
+          exit 1
+        fi
+        
+        # 3. Permissions and Sync
+        echo 'Applying permissions and syncing to $SYNC_FOLDER...'
+        sudo chown -R service_words:service_words \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\"
+        sudo find \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\" -type f -exec chmod 644 {} +
+        sudo find \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\" -type d -exec chmod 755 {} +
+        
+        # Protect source during sync and execute rsync
+        sudo chattr +i \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\"
+        sudo rsync -a --delete \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER/\" \"$SYNC_FOLDER/\"
+        sudo chattr -i \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\"
+        
+        echo 'Remote sync successful.'
+      "
+    - echo "Documentation deployment complete."
