CI improvements. LFS fix

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,24 +1,5 @@
-# This file is a template, and might need editing before it works on your project.
-# This is a sample GitLab CI/CD configuration file that should run without any modifications.
-# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
-# it uses echo commands to simulate the pipeline execution.
-#
-# A pipeline is composed of independent jobs that run scripts, grouped into stages.
-# Stages run in sequential order, but jobs within stages run in parallel.
-#
-# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
-#
-# You can copy and paste this template into a new `.gitlab-ci.yml` file.
-# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
-#
-# To contribute improvements to CI/CD templates, please follow the Development guide at:
-# https://docs.gitlab.com/ee/development/cicd/templates.html
-# This specific template is located at:
-# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
-image: docker:latest
-
 variables:
-  GIT_DEPTH: 20
+  GIT_DEPTH: 1
   LANG: C.UTF-8
   LC_ALL: C.UTF-8
   COPY_USER_NAME: service_words
@@ -38,140 +19,151 @@ variables:
   SYNC_TYPE: words # "words" (https://docs.aspose.com/words/) or "words-qa" (https://docs.aspose.com/words-qa/)
   SYNC_FOLDER: /var/www/docs.aspose.com/html/$SYNC_TYPE
   BRANCH_NAME: master
+  DOCKER_TLS_CERTDIR: "/certs"
+  # GIT_SSL_NO_VERIFY: "true"  # Add this line to ignore SSL verification, because we have self-signed certificate
 
 stages:
   - build
   - copy-docs
   - sync-docs
 
+default:
+  tags:
+    - documentation
+    - words
+
+.rules:branch:
+  rules:
+    - if: "$CI_COMMIT_BRANCH == $BRANCH_NAME"
+      when: on_success
+    - when: never
+
+.scripts:
+  apk_cache_setup: &apk_cache_setup
+    - mkdir -p .apk-cache
+    - export APK_CACHE_DIR="$(pwd)/.apk-cache"
+    - mkdir -p /etc/apk
+    - echo "cache-dir = $APK_CACHE_DIR" > /etc/apk/apk.conf
+
 build-docs-job:
   stage: build
-  image: node:20.15.1-alpine
-  tags:
-    - docker
-    - words
+  image: node:25.9-alpine
+  extends: .rules:branch
+  cache:
+    key: "$CI_COMMIT_REF_SLUG-apk-npm"
+    paths:
+      - .apk-cache/
+      - .npm-cache/
+    policy: pull-push
   before_script:
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Tune the environment..."
-    - sed -i 's/https/http/' /etc/apk/repositories
-    - apk update
-    - apk add --no-cache openssl ca-certificates
-    - sed -i 's/http/https/' /etc/apk/repositories
-    - update-ca-certificates --fresh
-    - mkdir -p $NPM_REGISTRY_CERT_DIR
-    - openssl s_client -showcerts -connect registry.npmjs.org:443 </dev/null 2>/dev/null | openssl x509 -outform PEM > $NPM_REGISTRY_CERT_PATH
-    - echo "HostName $(hostname), RunnerDescription $CI_RUNNER_DESCRIPTION, ProjectDirectory $CI_PROJECT_DIR, Git Depth $GIT_DEPTH, Docs template url $DOCS_TEMPLATE_GIT_URL, Docs template path $DOCS_TEMPLATE_CONTAINER_PATH, The current branch is $CI_COMMIT_REF_NAME"
-    - echo "Installing Git..."
-    - apk update && apk add --no-cache git
+    - echo "Tune the environment..."
+    - *apk_cache_setup
+    - npm config set cache "$CI_PROJECT_DIR/.npm-cache"
+    # - sed -i 's/https/http/' /etc/apk/repositories
+    # - apk update
+    # - apk add --no-cache openssl ca-certificates
+    # - sed -i 's/http/https/' /etc/apk/repositories
+    # - update-ca-certificates --fresh
+    # - mkdir -p $NPM_REGISTRY_CERT_DIR
+    # - openssl s_client -showcerts -connect registry.npmjs.org:443 </dev/null 2>/dev/null | openssl x509 -outform PEM > $NPM_REGISTRY_CERT_PATH
+    # - echo "HostName $(hostname), RunnerDescription $CI_RUNNER_DESCRIPTION, ProjectDirectory $CI_PROJECT_DIR, Git Depth $GIT_DEPTH, Docs template url $DOCS_TEMPLATE_GIT_URL, Docs template path $DOCS_TEMPLATE_CONTAINER_PATH, The current branch is $CI_COMMIT_REF_NAME"
+    # - echo "Installing Git..."
+    # - apk update && apk add --no-cache git
     - echo "The current branch is $CI_COMMIT_REF_NAME"
-    - echo "Install glibc for Hugo extended"
-    - apk add --no-cache gcompat libstdc++
-    - apk add --no-cache tar
-    - apk add git-lfs
+    - apk add gcompat libstdc++ tar git-lfs
     - git lfs install
-    - git --version
-    - git lfs version
-    - node --version
-    - npm --version
-    - tar --version
-    - apk info gcompat
-    - apk info libstdc++
+    - git lfs pull
+    # - git --version
+    # - git lfs version
+    # - node --version
+    # - npm --version
+    # - tar --version
+    # - apk info gcompat
+    # - apk info libstdc++
     - chmod +x $HUGO_PATH
     - $HUGO_PATH version
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Tune has finished."
+    - echo "Tune has finished."
   script:
-    - echo "Navifate to docs template repository location..."
+    - echo "Navigate to docs template repository location..."
     - mkdir -p $DOCS_TEMPLATE_CONTAINER_PATH
     - cd $DOCS_TEMPLATE_CONTAINER_PATH
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Fetch docs template repository..."
+    - echo "Fetch docs template repository..."
     - git clone --depth $GIT_DEPTH https://$DOCS_TAMPLATE_PROJECT_NAME:$DOCS_TEMPLATE_CI_CD_ACCESS_TOKEN@$DOCS_TEMPLATE_GIT_URL .
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Checkout template $DOCS_TEMPLATE_BRANCH_NAME branch..."
+    - echo "Checkout template $DOCS_TEMPLATE_BRANCH_NAME branch..."
     - git checkout $DOCS_TEMPLATE_BRANCH_NAME
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Currently on docs template checked out $(git rev-parse HEAD) revision"
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Replace content path in the docs.aspose.com-words.toml..."
+    - echo "Currently on docs template checked out $(git rev-parse HEAD) revision"
+    - echo "Replace content path in the docs.aspose.com-words.toml..."
     - sed -i "s|../md-words|$CI_PROJECT_DIR|g" ./configs/docs.aspose.com-words.toml
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Current directory $(pwd)"
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Intalling project dependencies..."
-    - npm config set strict-ssl false
-    - npm config set registry http://registry.npmjs.org/
-    - npm config set cafile $NPM_REGISTRY_CERT_PATH
+    - echo "Current directory $(pwd)"
+    - echo "Intalling project dependencies..."
+    # - npm config set strict-ssl false
+    # - npm config set registry http://registry.npmjs.org/
+    # - npm config set cafile $NPM_REGISTRY_CERT_PATH
     - npm config set registry https://registry.npmjs.org
     - npm ci
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Documentation build started..."
+    - echo "Documentation build started..."
     - $HUGO_PATH --cleanDestinationDir --source $DOCS_TEMPLATE_CONTAINER_PATH --baseURL https://docs.aspose.com/$SYNC_TYPE --contentDir $CI_PROJECT_DIR --config config.toml,configs/docs.aspose.com-words.toml --destination $DOCS_BUILD_OUTPUT --minify --verbose
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Documentation build complete, path in the container $DOCS_BUILD_OUTPUT"
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Compress generated documentation..."
+    - echo "Documentation build complete, path in the container $DOCS_BUILD_OUTPUT"
+    - echo "Compress generated documentation..."
     - cd $CI_HOME_FOLDER
     - mkdir -p $DOCS_BUILD_OUTPUT_ARCHIVE
     - tar --warning=all -czvf $DOCS_FULL_ARCHIVE_NAME ./$DOCS_BUILD_OUTPUT_FOLDER > /dev/null
     - mv ./$DOCS_FULL_ARCHIVE_NAME $DOCS_BUILD_OUTPUT_ARCHIVE/$DOCS_FULL_ARCHIVE_NAME
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Documentation compressed."
+    - echo "Documentation compressed."
   artifacts:
     paths:
       - $DOCS_BUILD_OUTPUT_ARCHIVE/$DOCS_FULL_ARCHIVE_NAME
     expire_in: 10 minutes
-  rules:
-    - if: $CI_COMMIT_BRANCH == $BRANCH_NAME
 
-copy-docs-job:
-  image: alpine:latest
-  stage: copy-docs
-  needs:
-  - job: build-docs-job
-  tags:
-    - docker
-    - words
-  before_script:
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Adding tools..."
-    - apk add --no-cache openssh-client # Install SSH client
-    - mkdir -p ~/.ssh # Add the private SSH key
-    - echo "$COPY_DOCS_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
-    - chmod 600 ~/.ssh/id_rsa
-    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config # Disable strict host key checking
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Tools has added and tuned."
-  script:
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Removing previous docs version..."
-    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "[ -d $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER ] && rm -rf $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER || echo 'Folder does not exist, skipping.'"
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Start copying generated docs..."
-    - scp $DOCS_BUILD_OUTPUT_ARCHIVE/$DOCS_FULL_ARCHIVE_NAME $COPY_USER_NAME@$COPY_SERVER_ADDRESS:$COPY_FOLDER
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Docs has copied to the $COPY_FOLDER"
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Unpack the docs"
-    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "tar -xzf $COPY_FOLDER/$DOCS_FULL_ARCHIVE_NAME -C $COPY_FOLDER && rm -rf $COPY_FOLDER/$DOCS_FULL_ARCHIVE_NAME"
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Copy complete"
-  rules:
-    - if: $CI_COMMIT_BRANCH == $BRANCH_NAME
 
-sync-docs-job:
+.ssh_setup:
   image: alpine:latest
-  stage: sync-docs
-  needs:
-  - job: copy-docs-job
-  tags:
-    - docker
-    - words
   before_script:
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Adding tools..."
+    - echo "Adding tools..."
     - apk add --no-cache openssh-client
     - mkdir -p ~/.ssh
     - echo "$COPY_DOCS_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Tools has added and tuned."
+    - echo "Tools has added and tuned."
+
+copy-docs-job:
+  stage: copy-docs
+  extends:
+    - .rules:branch
+    - .ssh_setup
+  needs:
+    - job: build-docs-job
+  script:
+    - echo "Removing previous docs version and preparing for copy..."
+    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "rm -rf $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER || true"
+    - echo "Start copying generated docs..."
+    - scp $DOCS_BUILD_OUTPUT_ARCHIVE/$DOCS_FULL_ARCHIVE_NAME $COPY_USER_NAME@$COPY_SERVER_ADDRESS:$COPY_FOLDER
+    - echo "Unpack the docs and cleanup archive..."
+    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "tar -xzf $COPY_FOLDER/$DOCS_FULL_ARCHIVE_NAME -C $COPY_FOLDER && rm -f $COPY_FOLDER/$DOCS_FULL_ARCHIVE_NAME"
+    - echo "Copy complete"
+
+sync-docs-job:
+  stage: sync-docs
+  extends:
+    - .rules:branch
+    - .ssh_setup
+  needs:
+    - job: copy-docs-job
   script:
     - |
-      if ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "[ -z \"\$(ls -A $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER)\" ]"; then
-        echo "Directory $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER is empty on the remote machine, failing the job."
-        exit 1
-      else
-        echo "Directory $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER has content on the docs machine, proceeding."
-      fi
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Syncing $SYNC_FOLDER started..."
-    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "sudo chown -R service_words:service_words $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER"
-    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "sudo find $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER -type f -exec chmod 644 {} \;"
-    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "sudo find $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER -type d -exec chmod 755 {} \;"
-    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "sudo chattr +i $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER" # lock folder for modifications.
-    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "sudo rsync -a --delete $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER/ $SYNC_FOLDER/"
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Syncing $SYNC_FOLDER has completed..."
-    - ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "sudo chattr -i $COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER"
-    - echo "$(date '+%Y-%m-%d %H:%M:%S') Rights have updated for the $SYNC_FOLDER..."
-  rules:
-    - if: $CI_COMMIT_BRANCH == $BRANCH_NAME
+      echo "Checking remote content and starting sync..."
+      ssh $COPY_USER_NAME@$COPY_SERVER_ADDRESS "
+        if [ ! -d \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\" ] || [ -z \"\$(ls -A \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\")\" ]; then
+          echo 'Source directory is empty or missing, failing.'
+          exit 1
+        fi
+        echo 'Syncing $SYNC_FOLDER...'
+        sudo chown -R service_words:service_words \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\" &&
+        sudo find \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\" -type f -exec chmod 644 {} \; &&
+        sudo find \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\" -type d -exec chmod 755 {} \; &&
+        sudo chattr +i \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\" &&
+        sudo rsync -a --delete \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER/\" \"$SYNC_FOLDER/\"
+        sudo chattr -i \"$COPY_FOLDER/$DOCS_BUILD_OUTPUT_FOLDER\"
+      "
+    - echo "Syncing and rights update for $SYNC_FOLDER completed."
